name: backend-test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Test GitHub Actions
        run: echo "GitHub Actions is working"